# fly.toml app configuration file generated for redux-anecdotes-megaeonise on 2025-07-12T17:31:30+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'redux-anecdotes-megaeonise'
primary_region = 'sin'

[build]
[env]
  PORT = "3001" 

[processes]
  app = "node server.js"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[deploy]
  strategy = "canary"


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[http_service.checks]]
  grace_period = "5s"
  interval = "10s"
  method = "GET"
  timeout = "3s"
  path = "/"