# fly.toml app configuration file generated for fullstackopen-redux-anecdotes-megaeonise on 2025-07-12T12:36:22+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fullstackopen-redux-anecdotes-megaeonise'
primary_region = 'sin'

[build]
[env]
  PORT = "3001" 

[processes]
  app = "json-server -p3001 -s ./dist --watch db.json"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
