name: Deployment pipeline

on:
  push:
    branches:
      - main
      - feature/commit_hash_on_success_message
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  blog_deployment_pipeline:
    env:
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI_BLOG }}
      MONGODB_URI: ${{ secrets.MONGODB_URI_BLOG }}
      PORT: ${{ secrets.PORT_BLOG }}
      SECRET: ${{ secrets.TEST_MONGODB_URI_BLOG }}
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: blog
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Backend setup
        run: |
          npm install
          npm run
      - name: Frontend setup
        run: |
          cd bloglist-frontend
          npm install --legacy-peer-deps
          npm run build
          cd ..
          cp -r bloglist-frontend/dist .
      # - name: e2e tests
      #   uses: cypress-io/github-action@v5
      #   with:
      #     env: TEST_MONGODB_URI=${{ secrets.TEST_MONGODB_URI_BLOG }}
      #     command: npm run test:e2e
      #     working-directory: blog
      #     start: npm run start:test
      #     wait-on: http://localhost:3003
  tested_blog_deployment_pipeline:
    env:
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI_BLOG }}
      MONGODB_URI: ${{ secrets.MONGODB_URI_BLOG }}
      PORT: ${{ secrets.PORT_BLOG }}
      SECRET: ${{ secrets.TEST_MONGODB_URI_BLOG }}
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: tested_blog
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Backend setup
        run: |
          npm install
          npm run
      - name: Frontend setup
        run: |
          ls
          cd bloglist-frontend
          npm install --legacy-peer-deps
          npm run build
          npm run test
          cd ..
          cp -r bloglist-frontend/dist .
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          env: TEST_MONGODB_URI=${{ secrets.TEST_MONGODB_URI_BLOG }}
          command: npm run test:e2e
          working-directory: tested_blog
          start: npm run start:test
          wait-on: http://localhost:3003

  anecdote_deployment_pipeline:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: redux-anecdotes
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Setup
        run: |
          npm install --legacy-peer-deps
          npm run lint
          npm run build

  tag_release:
    if: ${{ !contains(toJson(github.event.commits.*.message), '#skip') && github.event_name == 'push' && success() }}
    needs:
      [
        blog_deployment_pipeline,
        anecdote_deployment_pipeline,
        tested_blog_deployment_pipeline,
      ]
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - run: echo "${{ !contains(toJson(github.event.commits.*.message), '#skip') && github.event_name == 'push' }}"
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@e528bc2b9628971ce0e6f823f3052d1dcd9d512c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
