# fly.toml app configuration file generated for full-stack-open-tested-bloglist-megaeonise on 2025-07-12T14:41:19+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'full-stack-open-tested-bloglist-megaeonise'
primary_region = 'sin'

[build]

[env]
  PORT = "3003" # add this where PORT matches the internal_port below

[processes]
  app = "node index.js"

[http_service]
  internal_port = 3003
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[deploy]
  strategy = "canary"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[http_service.checks]]
  grace_period = "5s"
  interval = "10s"
  method = "GET"
  timeout = "3s"
  path = "/"
